name: 'Setup Nix + Cachix'
description: 'Installe Nix et active le cache Cachix tbracquart'

runs:
  using: 'composite'
  steps:
    - uses: cachix/install-nix-action@v31.11.1
      with:
        github_access_token: '${{ env.GITHUB_TOKEN }}'
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Activer le cache Cachix 📦
      uses: cachix/cachix-action@v17
      with:
        name: tbracquart
        authToken: '${{ env.CACHIX_AUTH_TOKEN }}'
