name: 'Setup Nix + Cachix'
description: 'Installe Nix et active le cache Cachix tbracquart'

runs:
  using: 'composite'
  steps:
    - uses: cachix/install-nix-action@v31.11.1
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= lantian:EeAUQ+W+6r7EtwnmYjeVwx5kOGEBpjlBfPlzGlTNvHc= freesmlauncher.cachix.org-1:Jcp5Q9wiLL+EDv8Mh7c6L9xGk+lXr7/otpKxMOuBuDs= tbracquart.cachix.org-1:eTT16nwdreuvu4yagVFB1p+PeRg8ZCZsCA8648IJCZU=
          substituters = https://cache.nixos.org https://nix-community.cachix.org https://xuyh0120.win https://freesmlauncher.cachix.org https://tbracquart.cachix.org

    - name: Activer le cache Cachix 📦
      uses: cachix/cachix-action@v17
      with:
        name: tbracquart
        authToken: '${{ env.CACHIX_AUTH_TOKEN }}'